apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nyxu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nyxu
    app.kubernetes.io/part-of: byoc-app-pvgg
  name: nyxu
spec:
  rules:
  - host: nyxu-byoc-xnky-tenant.apps.b8018988a6778f4eea8a.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: nyxu
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
