apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nyxu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nyxu
    app.kubernetes.io/part-of: byoc-app-pvgg
  name: nyxu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: nyxu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: nyxu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-xnky-tenant/byoc-app-pvgg/nyxu@sha256:816de0529e63372ca0e4d93e3dc6c4bd806f9d68324723a505192685bce24296
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
