apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nyxu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nyxu
    app.kubernetes.io/part-of: byoc-app-pvgg
  name: nyxu
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: nyxu
status:
  loadBalancer: {}
